### ISSUE TITLE
"Getter getIsTest or isIsTest for object does not exists"

### ISSUE THREAD

**Issue by ZubyakDR** [kassacom/php-sdk#3]
You changed code of class SettingsRequestIte
and now always code throw Exception
https://github.com/kassacom/php-sdk/commit/3f7bc889a3f4fe71199a71c9f93a413f5c3b3fed

Uncaught PHP Exception KassaCom\SDK\Exception\Validation\BadGetterException [#5b8cfdf518d8b]: "Getter getIsTest or isIsTest for object does not exists" at kassacom/php-sdk/src/Actions/ObjectRecursiveValidator.php line 144 {"exception":"KassaCom\\SDK\\Exception\\Validation\\BadGetterException","trace":"#0 kassacom/php-sdk/src/Actions/ObjectRecursiveValidator.php(42): KassaCom\\SDK\\Actions\\ObjectRecursiveValidator::getFieldValue(Object(KassaCom\\SDK\\Model\\Request\\Item\\SettingsRequestItem), 'is_test')\n#1 kassacom/php-sdk/src/Actions/ObjectRecursiveValidator.php(121): KassaCom\\SDK\\Actions\\ObjectRecursiveValidator::validate(Object(KassaCom\\SDK\\Model\\Request\\Item\\SettingsRequestItem))\n#2 kassacom/php-sdk/src/Actions/ObjectRecursiveValidator.php(37): KassaCom\\SDK\\Actions\\ObjectRecursiveValidator::validateValue(Object(KassaCom\\SDK\\Model\\Request\\Item\\SettingsRequestItem), 'settings', 'KassaCom\\\\SDK\\\\Mo...')\n#3 kassacom/php-sdk/src/Client.php(122): KassaCom\\SDK\\Actions\\ObjectRecursiveValidator::validate(Object(KassaCom\\SDK\\Model\\Request\\Payment\\CreatePaymentRequest))\n#4 ....

And we can not use your version repository.

**Comment by devkassacom** [comment]
Not actual anymore... Thanks
